version: '3.9'

services:
    app:
        build:
            context: docker/app
            dockerfile: Dockerfile
            args:
                USER: ${CONTAINER_USER_NAME}
                GROUP: ${CONTAINER_GROUP_NAME}
                UID: ${LOCAL_UID}
                GID: ${LOCAL_GID}
        container_name: ${CONTAINER_BASE_NAME}_app
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.`${CONTAINER_BASE_NAME}`.rule=Host(`${HOST_APP}`)" # domain to expose on
            - "traefik.docker.network=traefik_proxy"
        ports:
            - '${FORWARDED_DEFAULT_PORT:-80}:80'
        volumes:
            - './:/var/www/app'
        networks:
            - default
            - traefik_proxy
        depends_on:
            - mariadb

    mariadb:
        image: mariadb
        container_name: ${CONTAINER_BASE_NAME}_mariadb
        labels:
            - "traefik.enable=false"
        ports:
            - '${FORWARDED_DB_PORT:-3306}:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - default

    mailhog:
        image: 'mailhog/mailhog:latest'
        container_name: ${CONTAINER_BASE_NAME}_mail
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.`${CONTAINER_BASE_NAME}`_mail.rule=Host(`${HOST_MAIL}`)" # domain to expose on\
            - "traefik.http.services.`${CONTAINER_BASE_NAME}`_mail.loadbalancer.server.port=8025"
            - "traefik.docker.network=traefik_proxy"
        ports:
            - '${FORWARDED_MAIL_PORT:-1025}:1025'
            - '${FORWARDED_MAIL_DASHBOARD_PORT:-8025}:8025'
        networks:
            - default
            - traefik_proxy

networks:
    default:
        driver: bridge
        name: ${CONTAINER_BASE_NAME}
    traefik_proxy:
        external: true

volumes:
    mariadb:
